
export const CHANGE_ALL = "CHANGE_ALL";
export const CHANGE_DATE_FOR_RENDERING = "CHANGE_DATE_FOR_RENDERING";
export const GET_ID_SELECTED_NEWS = "GET_ID_SELECTED_NEWS";
export const CHANGE_NAME_CALL_API = "CHANGE_NAME_CALL_API";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const TURN_HOME_PAGE = "TURN_HOME_PAGE";

